apiVersion: apps/v1
kind: Deployment
metadata:
  name: new_deployment
spec:
  replicas: 10 
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx_html
        image: abudevops194/my_kube
        ports:
        - containerPort: 80
